server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _; # _ = localshost
    server_tokens off;

    root /app/src;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string; # Redirect all requests to index.php
    }

    # ALIASY
    location /css/ {
        alias /app/public/css/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location /js/ {
        alias /app/public/js/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    location /views/ {
        alias /app/public/views/;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /(controllers|models|repositories|services)/ {
        deny all;
        return 403;
    }
}